apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-claim
  namespace: api
spec:
  volumeName: volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500M
