apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: api
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: manhhoangseta/devops-nodejs-app:fde58a6bb0bcdb0c7c6c5a1fbd2c5767967ae76b
          command: ["nodejs", "app.js"]
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            exec:
              command:
                - "true"
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 15
