apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-nodeport
  namespace: api
spec:
  selector:
    app: nodejs-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30036
      protocol: TCP
